apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ribbon-discovery-deployment
  labels:
    app: ribbon-discovery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ribbon-discovery
  template:
    metadata:
      labels:
        app: ribbon-discovery
    spec:
      containers:
      - name: ribbon-discovery
        image: th3pu1/ribbon-discovery
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080